name: coverage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Run tests
        run: npm test
      - name: Upload coverage
        env:
          TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: ./node_modules/.bin/codecov --token=$TOKEN
